Fix Windows build: move platform includes outside namespace
Move #include <windows.h> and Unix headers (fcntl.h, sys/file.h)
to the top of the file, BEFORE the namespace miq {} block.

Previously, windows.h was included INSIDE the miq namespace at line 546,
which caused all Windows SDK symbols (including std:: definitions) to be
pulled into the miq namespace, creating miq::std:: symbols. This caused
MSVC to fail with errors like:
  error C2061: syntax error: identifier 'bidirectional_iterator_tag'
  note: miq::std::_List_unchecked_const_iterator

Fix: Include all platform headers before namespace declaration.